name: DLT Pipeline Deploy Dev
concurrency: 1
on:
  push:
    branches:
      - develop

env:
  DATABRICKS_TOKEN: ${{ secrets.E2_SP_TOKEN }}
  DATABRICKS_BUNDLE_ENV: dev

jobs:
  deploy:
    name: "Setup Config and deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Bundle
        id: deploy_bundle
        run: databricks bundle deploy

  pipeline_update:
    name: "Run DLT Pipeline update"
    runs-on: ubuntu-latest

    needs:
      - deploy
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle run dab_demo_pipeline
